name: infotech
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^0.6.1+4
  carousel_pro: ^1.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_storage: ^3.0.4
  
  flutter_speed_dial: ^1.2.1
  cloud_firestore: ^0.12.9+1
  firebase_database: ^3.0.7
  
  photo_view: ^0.4.2
  
  double_back_to_close_app: ^0.1.1

  image_cropper: ^1.0.2
  flutter_image_compress: ^0.6.3
  firebase_auth: ^0.14.0+5


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/j.jpg
    - assets/food1.jpeg
    - assets/food2.jpeg
    - assets/food3.jpeg
    - assets/food4.jpeg
    - assets/food5.jpeg
    - assets/food6.jpeg
    - assets/food7.jpeg
    - assets/food8.jpeg
    - assets/food9.jpeg
    - assets/food10.jpeg
    - assets/food11.jpeg
    - assets/food12.jpg
  
    - assets/new1.jpg
    - assets/new2.jpg
    - assets/new3.jpg
    - assets/new4.jpg
    - assets/new5.jpg
    - assets/new6.jpg
    - assets/new7.jpg
    - assets/new8.jpg
    - assets/new9.jpg
    - assets/new10.jpg
    - assets/new11.jpg
    - assets/j.jpg
    - assets/j2.jpg
    - assets/nn.jpg
    - assets/nn1.jpg
    - assets/nn2.jpg
    - assets/nn3.jpg
    - assets/nn5.jpg
    - assets/s1.jpg
    - assets/s2.jpg
    - assets/s3.jpg
    - assets/s4.jpg
    - assets/s5.jpg
    - assets/s6.jpg
    - assets/s7.jpg
    - assets/s8.jpg
    - assets/s9.jpg
    - assets/s10.jpg
    - assets/f1.jpg
    - assets/f2.jpg
    - assets/f3.jpg
    - assets/f4.jpg
    - assets/f5.jpg
    - assets/f6.jpg
    - assets/f7.jpg
    - assets/f8.jpg
    - assets/f9.jpg
    
    
    - assets/cm1.jpeg
    - assets/cm2.jpeg
    - assets/cm3.jpeg
    - assets/cm4.jpeg 
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
